# Generated by Django 6.0 on 2026-02-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
    ]
