# Generated by Django 6.0 on 2026-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mark_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
